name: maher_law_app
description: "الوسيط القانوني."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  equatable: ^2.0.7
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_inappwebview: ^6.1.5
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.4.1
  flutter_quill: ^11.4.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^16.2.1
  google_fonts: ^6.2.1
  intl: 0.20.2
  lottie: ^3.3.1
  morphable_shape: ^2.0.0
  provider: ^6.1.2
  responsive_sizer: ^3.3.1
  seo_renderer: ^0.6.0
  sidebarx: ^0.17.1
  simple_circular_progress_bar: ^1.0.2
  url_launcher: ^6.3.1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lotties/
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Black.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #       - asset: assets/fonts/Cairo-SemiBold.ttf
